import os
import json
from datetime import datetime
from typing import Dict, List, Any, Optional
import logging

logger = logging.getLogger(__name__)

class ReportExporter:
    """
    Exports ResearchResult and KnowledgeGraph data to structured Markdown
    """
    
    def __init__(self, export_dir: str = "./exports"):
        self.export_dir = export_dir
        if not os.path.exists(self.export_dir):
            os.makedirs(self.export_dir)
            
    def export_to_markdown(self, research_data: Dict[str, Any], filename: Optional[str] = None) -> str:
        """
        Convert research findings to a professional Markdown report
        """
        query = research_data.get("query", "Untitled Research")
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        if not filename:
            safe_query = "".join([c if c.isalnum() else "_" for c in query[:30]])
            filename = f"research_{safe_query}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
            
        filepath = os.path.join(self.export_dir, filename)
        
        # Build Markdown content
        md = [
            f"# Research Report: {query}",
            f"*Generated by MentorZero on {timestamp}*",
            "",
            "## Executive Summary",
            f"Comprehensive research analysis conducted on the topic: **{query}**.",
            f"Calculated confidence score: `{research_data.get('confidence', 0):.2f}`",
            "",
            "---",
            "",
            "## Key Findings & Verified Facts",
        ]
        
        # Add facts
        facts = research_data.get("facts", [])
        if facts:
            for fact in facts[:20]:
                md.append(f"- {fact}")
        else:
            md.append("*No specific facts extracted.*")
            
        md.append("")
        md.append("## Knowledge Graph Entities")
        
        # Add graph summary
        graph = research_data.get("knowledge_graph", {})
        entities = graph.get("entities", [])
        if entities:
            md.append("| Entity | Type | Importance |")
            md.append("| --- | --- | --- |")
            
            # Use type ignore to satisfy current checker for list slicing on unknown type
            sorted_ents = sorted(entities, key=lambda x: x.get("weight", 0), reverse=True) # type: ignore
            for ent in sorted_ents[:15]: # type: ignore
                md.append(f"| {ent.get('name')} | {ent.get('type', 'General')} | {ent.get('weight', 1)} |")
        else:
            md.append("*Knowledge graph data not available for this session.*")
            
        md.append("")
        md.append("## Sources & References")
        
        # Add sources
        sources = research_data.get("sources", [])
        if sources:
            for src in sources[:10]:
                title = src.get("title", "Source")
                url = src.get("url", "#")
                snippet = src.get("snippet", src.get("content", ""))[:150]
                md.append(f"### [{title}]({url})")
                md.append(f"> {snippet}...")
                md.append("")
        else:
            md.append("*No external sources referenced.*")
            
        md.append("\n---")
        md.append("*End of MentorZero Research Report*")
        
        content = "\n".join(md)
        
        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            logger.info(f"Report exported to {filepath}")
            return filepath
        except Exception as e:
            logger.error(f"Failed to export report: {e}")
            return ""

# Basic Singleton
report_exporter = ReportExporter()
